#include <stdio.h>

int main()
{	
	// -- Reading a text file -- 
	// files are open with the file pointer type FILE*
	FILE* fp;
	int c;
	char s[1024];
	int linecount = 0;
	fp = fopen("hello.txt", "r");


	// Notice that fgetc is stored in an int !!
	// EOF is a the special invisible char that denotes the end of a file
	while ((c = fgetc(fp)) != EOF)
		printf("%c", c);

	fclose(fp);

	fp = fopen("quote.txt", "r");

	/* fgets will get the string in a txt
	The trick to read one line at a time is
	to use fgets with a while loop untill the
	char is NULL */
	while (fgets(s, sizeof s, fp) != NULL)
		printf("%d: %s", ++linecount, s);

	// args of fgets : char* string, int max length, file*

 	fclose(fp);

 	// -- Formatted Input --
 	// You can format information in a txt and access it via fscanf

 	fp = fopen("whales.txt", "r");
 	float length;
 	int mass;
 	char name[1024];


	while (fscanf(fp, "%s %f %d", name, &length, &mass) != EOF)
		printf("%s whale, %d tonne, %.1f meters\n", name, mass, length);
	// Args of fscanf (*FILE, string format, variables)
	// while loop can be used again to scan the whole file
	// Fun fact : %f can be used with .x before to limit the number of decimals
	/* !!-- fscanf is dangerous function in the sens
 	 that it can easily lead to memory leaks in case the 
 	 string use differs from the expected format --!!*/
	/* It is acceptable to use it if the strings are trustable
	to be formatted in a certain way like in a txt generated by
	your program. Otherwise we will see later how to secure
	untrusted input (eg user input) with funcs like strtol or strtod */

	fclose(fp);

	// -- Writting Text Files -- 
	int x = 32;
	fp = fopen("output.txt", "w");

	// fputc, fprintf and fputs can be used to write in a file
	fputc('B', fp);
	fputc('\n', fp);
	fprintf(fp, "x = %d\n", x);
	fputs("Hello world!\n", fp);

	fclose(fp);
	// You can use stdout to write the output on the console
	// stdout is a file !
	fp = stdout;

	// fputc, fprintf and fputs can be used to write in a file
	fputc('B', fp);
	fputc('\n', fp);
	fprintf(fp, "x = %d\n", x);
	fputs("Hello world!\n", fp);

	fclose(fp);

	// -- Readin Binaries -- 
	// To interact a file binaries, simply add "b" in the mode "rb", "wb"
	fp = fopen("output.bin", "wb");

	unsigned char bytes[6] = {5, 37, 0, 88, 255, 12};
	// args : data, size of each data, number of data, FILE*
	fwrite(bytes, sizeof(char), 6, fp);

	fclose(fp);

	fp = fopen("output.bin", "rb");
	unsigned char k;
	while (fread(&k, sizeof(char), 1, fp) > 0)
		printf("%d\n", k);

	fclose(fp);
	return 0;
}